const config = {
  WINDOW_WIDTH: 800,
  WINDOW_HEIGHT: 600,
  MIN_CONFIDENCE: 0.5,
  MIN_KEYPOINT_SCORE_ACCEPTED: 0.1,
  START_DELAY: 1e4,
  COLLECT_DATA_INPUT: 'COLLECT_DATA',
  WEBCAM_READY_CODE: 4,
  POSE_ESTIMATION_INTERVAL: 100,
};

export default config;
